# Generated by Django 6.0.1 on 2026-05-28 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_sharedmaterial'),
        ('japanese_exam', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_category', models.CharField(choices=[('caregiving', 'Caregiving: Long-term Care Specified Skilled Worker Evaluation Test'), ('agriculture', 'Agriculture: Agriculture Skill Assessment Test (Crop and Livestock)'), ('food_services', 'Food Services: Food Service Industry Skill Test'), ('food_beverage', 'Food & Beverage: Food and Beverage Manufacturing Industry Skill Test'), ('construction', 'Construction: Construction Field Evaluation Test'), ('accommodation', 'Accommodation: Accommodation Industry Proficiency Test'), ('automobile', 'Automobile: Automobile Repair and Maintenance Field Skill Test'), ('manufacturing', 'Manufacturing: Industrial Product Manufacturing Field (Machining, Electronics, Metal Processing)'), ('fishery_aquaculture', 'Fishery & Aquaculture: Fishing Industry Skills Proficiency Test'), ('building_cleaning', 'Building Cleaning: Building Cleaning Management Field Test'), ('others', 'Others: Shipbuilding, Aviation, Forestry, Wood Industry')], max_length=30)),
                ('status', models.CharField(blank=True, choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=4, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_exam_results', to='dashboard.student')),
            ],
            options={
                'unique_together': {('student', 'skill_category')},
            },
        ),
    ]
