# Generated by Django 4.2.27 on 2026-08-02 08:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('japanese_exam', '0002_skillexamresult'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examresult',
            options={'ordering': ['-exam_date', '-attempt_number', '-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='examresult',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='examresult',
            name='attempt_number',
            field=models.PositiveIntegerField(default=1, verbose_name='Attempt Number'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='exam_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Exam Date'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='remarks',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Remarks/Notes'),
        ),
    ]
