# Generated by Django 4.2.27 on 2025-12-24 05:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDemandLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('pdf_file', models.FileField(upload_to='job_demand_letters/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_letters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Demand Letter',
                'verbose_name_plural': 'Job Demand Letters',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
