# Generated by Django 4.2.27 on 2026-03-31 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pdf_file', models.FileField(upload_to='assignment_templates/')),
                ('qr_x', models.FloatField(default=100, help_text='X coordinate for QR placement (points)')),
                ('qr_y', models.FloatField(default=100, help_text='Y coordinate for QR placement (points)')),
                ('qr_page', models.PositiveIntegerField(default=1, help_text='Page number for QR placement (1-indexed)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ISBN'),
        ),
        migrations.CreateModel(
            name='BookAssignment',
            fields=[
                ('id', models.CharField(help_text='Unique Assignment ID', max_length=50, primary_key=True, serialize=False)),
                ('recipient_name', models.CharField(max_length=255)),
                ('recipient_id', models.CharField(blank=True, help_text='Student ID or similar', max_length=100, null=True)),
                ('assignment_qr', models.ImageField(blank=True, null=True, upload_to='assignment_qrs/')),
                ('final_pdf', models.FileField(blank=True, null=True, upload_to='assigned_books_pdfs/')),
                ('returned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='books.book')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.assignmenttemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
