# Generated by Django 4.2.27 on 2026-03-31 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmenttemplate',
            name='id_x',
            field=models.FloatField(default=0, help_text='X for Book ID'),
        ),
        migrations.AddField(
            model_name='assignmenttemplate',
            name='id_y',
            field=models.FloatField(default=0, help_text='Y for Book ID'),
        ),
        migrations.AddField(
            model_name='assignmenttemplate',
            name='name_x',
            field=models.FloatField(default=0, help_text='X for Book Name'),
        ),
        migrations.AddField(
            model_name='assignmenttemplate',
            name='name_y',
            field=models.FloatField(default=0, help_text='Y for Book Name'),
        ),
    ]
