# Generated by Django 4.2.27 on 2026-03-31 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_assignmenttemplate_id_x_assignmenttemplate_id_y_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmenttemplate',
            name='qr_size',
            field=models.PositiveIntegerField(default=150, help_text='Size of QR code (points)'),
        ),
    ]
