# Generated by Django 4.2.27 on 2026-04-02 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_assignmenttemplate_qr_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmenttemplate',
            name='qr_size',
            field=models.PositiveIntegerField(default=300, help_text='Size of QR code (points)'),
        ),
    ]
