# Generated by Django 6.0.1 on 2026-04-06 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_assignmenttemplate_qr_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookassignment',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='Mark as paid if book deposit/fee is collected'),
        ),
        migrations.AddField(
            model_name='bookassignment',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about this assignment', null=True),
        ),
        migrations.AddField(
            model_name='bookassignment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
