# Generated by Django 6.0.1 on 2026-04-15 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_assignmenttemplate_qr_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookassignment',
            name='final_image',
            field=models.ImageField(blank=True, null=True, upload_to='assigned_books_images/'),
        ),
    ]
