# Generated by Django 6.0.1 on 2026-05-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_bookassignment_final_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookassignment',
            name='printed_book_name',
            field=models.CharField(blank=True, help_text='Custom book name as printed (if different from actual book)', max_length=255, null=True),
        ),
    ]
