# Generated by Django 6.0.1 on 2026-05-17 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_bookassignment_printed_book_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookassignment',
            name='printed_book_name',
        ),
    ]
