# Generated by Django 4.2.27 on 2026-01-04 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0013_merge_20251126_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisaTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('applied', 'Applied'), ('processing', 'Processing'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('stamped', 'Stamped')], default='not_started', max_length=20)),
                ('application_number', models.CharField(blank=True, max_length=50, null=True)),
                ('applied_date', models.DateField(blank=True, null=True)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('interview_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visa_tracking', to='dashboard.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='COETracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('processing', 'Processing'), ('approved', 'Approved'), ('issued', 'Issued'), ('delivered', 'Delivered'), ('rejected', 'Rejected')], default='not_started', max_length=20)),
                ('coe_number', models.CharField(blank=True, max_length=50, null=True)),
                ('applied_date', models.DateField(blank=True, null=True)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coe_tracking', to='dashboard.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
