# Generated by Django 4.2.27 on 2026-01-20 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coe_visa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visatracking',
            name='visa_document',
            field=models.FileField(blank=True, null=True, upload_to='visa_documents/'),
        ),
    ]
