# Generated by Django 4.2.27 on 2026-01-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coe_visa', '0002_visatracking_visa_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='visatracking',
            name='arrival_airport',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='visatracking',
            name='departure_airport',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='visatracking',
            name='ticket_file',
            field=models.FileField(blank=True, null=True, upload_to='ticket_files/'),
        ),
        migrations.AddField(
            model_name='visatracking',
            name='transit_airport',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
