# Generated by Django 6.0.1 on 2026-03-23 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreementdocx', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='year',
            field=models.IntegerField(blank=True, default=2026, null=True),
        ),
    ]
