# Generated by Django 4.2.27 on 2025-12-12 06:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('max_capacity', models.IntegerField(default=1)),
                ('booked_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('address', models.TextField()),
                ('company_name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('appointment_aim', models.CharField(choices=[('consultation', 'Consultation'), ('meeting', 'Business Meeting'), ('interview', 'Interview'), ('demo', 'Product Demo'), ('support', 'Technical Support'), ('other', 'Other')], max_length=50)),
                ('message', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmation_code', models.CharField(max_length=20, unique=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('appointment_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.appointmentslot')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
