# Generated by Django 5.2.7 on 2025-10-26 07:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True, verbose_name='Student ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(16), django.core.validators.MaxValueValidator(100)], verbose_name='Age')),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=10)),
                ('permanent_address', models.TextField(verbose_name='Permanent Address')),
                ('present_address', models.TextField(verbose_name='Present Address')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email ID')),
                ('phone', models.CharField(max_length=15, verbose_name='Phone No.')),
                ('height', models.CharField(max_length=10, verbose_name='Height')),
                ('weight', models.CharField(max_length=10, verbose_name='Weight')),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('tb_test', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative')], max_length=10, verbose_name='TB Test Result')),
                ('medical_report', models.TextField(blank=True, verbose_name='Medical Report')),
                ('passport_no', models.CharField(max_length=20, unique=True, verbose_name='Passport No.')),
                ('passport_issue_date', models.DateField(verbose_name='Date of Issue')),
                ('passport_expiry_date', models.DateField(verbose_name='Date of Expiry')),
                ('visa_apply_record', models.BooleanField(default=False, verbose_name='Visa Apply Record')),
                ('visa_details', models.TextField(blank=True, verbose_name='Visa Apply Details')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='student_photos/', verbose_name='Candidate Photo')),
                ('spouse_name', models.CharField(blank=True, max_length=100, verbose_name='Spouse Name')),
                ('spouse_contact', models.CharField(blank=True, max_length=15, verbose_name='Spouse Contact No.')),
                ('driving_license', models.CharField(blank=True, max_length=50, verbose_name='Driving License')),
                ('license_pass_year', models.CharField(blank=True, max_length=20, verbose_name='License Pass Year')),
                ('license_discretion', models.TextField(blank=True, verbose_name='Discretion of License')),
                ('hobbies', models.TextField(blank=True, verbose_name='Hobbies and Special Skills')),
                ('motivation', models.TextField(blank=True, verbose_name='Motivation and Self-promotion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EducationalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('primary', 'Primary School'), ('junior', 'Junior High School'), ('higher', 'Higher Secondary School'), ('college', 'College/University'), ('graduate', 'Graduate University'), ('other', 'Other School')], max_length=20, verbose_name='Pass Level')),
                ('school_name', models.CharField(max_length=200, verbose_name='Name of School')),
                ('admission_year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)], verbose_name='Admission Year')),
                ('admission_month', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Admission Month')),
                ('graduation_year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)], verbose_name='Graduation Year')),
                ('graduation_month', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Graduation Month')),
                ('enrolled_years', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Enrolled Years')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educational_history', to='dashboard.student')),
            ],
            options={
                'verbose_name': 'Educational History',
                'verbose_name_plural': 'Educational History',
                'ordering': ['admission_year'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_name', models.CharField(max_length=200, verbose_name='Name of Certificate')),
                ('pass_year', models.CharField(max_length=20, verbose_name='Pass Year & Month')),
                ('organization', models.CharField(max_length=200, verbose_name='Organization')),
                ('join_year', models.CharField(max_length=20, verbose_name='Join Year and Month')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='dashboard.student')),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
            },
        ),
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('bio_data', 'Student BIO-DATA'), ('id_info', 'Student ID Information'), ('educational', 'Student Educational Doc'), ('report', 'Student Report'), ('other', 'Other PDF')], max_length=20)),
                ('document_file', models.FileField(upload_to='student_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='dashboard.student')),
            ],
            options={
                'verbose_name': 'Student Document',
                'verbose_name_plural': 'Student Documents',
            },
        ),
        migrations.CreateModel(
            name='WorkingExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_type', models.CharField(max_length=100, verbose_name='Type of Work')),
                ('company_name', models.CharField(max_length=200, verbose_name='Name of Working Company')),
                ('join_date', models.DateField(verbose_name='Date of Join')),
                ('resign_date', models.DateField(blank=True, null=True, verbose_name='Date of Resign')),
                ('working_years', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Working Years')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_experience', to='dashboard.student')),
            ],
            options={
                'verbose_name': 'Working Experience',
                'verbose_name_plural': 'Working Experience',
                'ordering': ['-join_date'],
            },
        ),
    ]
