# Generated by Django 5.2.7 on 2025-10-29 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('dob', models.DateField()),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=10)),
                ('permanent_address', models.TextField()),
                ('present_address', models.TextField(blank=True, null=True)),
                ('passport_no', models.CharField(blank=True, max_length=30, null=True)),
                ('passport_issue', models.DateField(blank=True, null=True)),
                ('passport_expiry', models.DateField(blank=True, null=True)),
                ('height', models.CharField(blank=True, max_length=20, null=True)),
                ('weight', models.CharField(blank=True, max_length=20, null=True)),
                ('medical_report', models.CharField(blank=True, max_length=100, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=5, null=True)),
                ('tb_status', models.CharField(blank=True, choices=[('positive', 'Positive'), ('negative', 'Negative')], max_length=10, null=True)),
                ('visa_apply', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=5, null=True)),
                ('visa_details', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='student_photos/')),
                ('spouse_name', models.CharField(blank=True, max_length=100, null=True)),
                ('spouse_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('primary_school', models.CharField(blank=True, max_length=100, null=True)),
                ('junior_school', models.CharField(blank=True, max_length=100, null=True)),
                ('high_school', models.CharField(blank=True, max_length=100, null=True)),
                ('college', models.CharField(blank=True, max_length=100, null=True)),
                ('university', models.CharField(blank=True, max_length=100, null=True)),
                ('graduate_university', models.CharField(blank=True, max_length=100, null=True)),
                ('other_school', models.CharField(blank=True, max_length=100, null=True)),
                ('type_of_work', models.CharField(blank=True, max_length=100, null=True)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('work_period', models.CharField(blank=True, max_length=50, null=True)),
                ('working_years', models.CharField(blank=True, max_length=20, null=True)),
                ('certificate_pass_year', models.CharField(blank=True, max_length=20, null=True)),
                ('certificate_name', models.CharField(blank=True, max_length=100, null=True)),
                ('language_join_year', models.CharField(blank=True, max_length=20, null=True)),
                ('organization', models.CharField(blank=True, max_length=100, null=True)),
                ('driving_license', models.CharField(blank=True, max_length=50, null=True)),
                ('license_pass_year', models.CharField(blank=True, max_length=20, null=True)),
                ('license_discretion', models.CharField(blank=True, max_length=100, null=True)),
                ('hobbies', models.TextField(blank=True, null=True)),
                ('motivation', models.TextField(blank=True, null=True)),
                ('biodata_doc', models.FileField(blank=True, null=True, upload_to='student_docs/')),
                ('id_info_doc', models.FileField(blank=True, null=True, upload_to='student_docs/')),
                ('education_doc', models.FileField(blank=True, null=True, upload_to='student_docs/')),
                ('report_doc', models.FileField(blank=True, null=True, upload_to='student_docs/')),
                ('extra_pdf', models.FileField(blank=True, null=True, upload_to='student_docs/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='educationalhistory',
            name='student',
        ),
        migrations.RemoveField(
            model_name='workingexperience',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentdocument',
            name='student',
        ),
        migrations.DeleteModel(
            name='Certificate',
        ),
        migrations.DeleteModel(
            name='EducationalHistory',
        ),
        migrations.DeleteModel(
            name='WorkingExperience',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='StudentDocument',
        ),
    ]
