# Generated by Django 5.2.7 on 2025-10-29 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_studentregistration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=150)),
                ('doc_file', models.FileField(upload_to='student_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EducationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=100)),
                ('group', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.CharField(blank=True, max_length=50, null=True)),
                ('result', models.CharField(blank=True, max_length=50, null=True)),
                ('year', models.CharField(blank=True, max_length=10, null=True)),
                ('board', models.CharField(blank=True, max_length=100, null=True)),
                ('institution', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FamilyEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(max_length=100)),
                ('father_mobile_no', models.CharField(blank=True, max_length=20, null=True)),
                ('father_nid', models.CharField(blank=True, max_length=50, null=True)),
                ('mother_name', models.CharField(max_length=100)),
                ('mother_mobile_no', models.CharField(blank=True, max_length=20, null=True)),
                ('mother_nid', models.CharField(blank=True, max_length=50, null=True)),
                ('education_status', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('photo', models.ImageField(upload_to='student_photos/')),
                ('permanent_address', models.TextField()),
                ('present_address', models.TextField(blank=True, null=True)),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=10)),
                ('passport_no', models.CharField(blank=True, max_length=50, null=True)),
                ('passport_issue_date', models.DateField(blank=True, null=True)),
                ('passport_expiry_date', models.DateField(blank=True, null=True)),
                ('height', models.CharField(blank=True, max_length=20, null=True)),
                ('weight', models.CharField(blank=True, max_length=20, null=True)),
                ('medical_report', models.TextField(blank=True, null=True)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True)),
                ('tb_status', models.CharField(blank=True, choices=[('positive', 'Positive'), ('negative', 'Negative')], max_length=10, null=True)),
                ('visa_apply_record', models.BooleanField(default=False)),
                ('visa_apply_details', models.TextField(blank=True, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=150)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='work_certificates/')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_certificates', to='dashboard.student')),
            ],
        ),
        migrations.DeleteModel(
            name='StudentRegistration',
        ),
        migrations.AddField(
            model_name='familyeducation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_educations', to='dashboard.student'),
        ),
        migrations.AddField(
            model_name='educationhistory',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_histories', to='dashboard.student'),
        ),
        migrations.AddField(
            model_name='document',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='dashboard.student'),
        ),
    ]
