# Generated by Django 5.2.7 on 2025-10-30 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_studentregistration_remove_educationhistory_student_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=100)),
                ('emp_salary', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='StudentRegistration',
        ),
    ]
