# Generated by Django 5.2.7 on 2025-10-31 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_employee_delete_studentregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_id', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('age', models.PositiveIntegerField()),
                ('marital_status', models.CharField(blank=True, max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='candidate_photos/')),
                ('permanent_address', models.TextField()),
                ('present_address', models.TextField(blank=True)),
                ('passport_no', models.CharField(blank=True, max_length=100)),
                ('date_of_issue', models.DateField(blank=True, null=True)),
                ('date_of_expiry', models.DateField(blank=True, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('eye_lens_right', models.CharField(blank=True, max_length=50)),
                ('eye_lens_left', models.CharField(blank=True, max_length=50)),
                ('blood_group', models.CharField(blank=True, max_length=10)),
                ('visa_apply_record', models.BooleanField(default=False)),
                ('visa_apply_result', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('family_records', models.TextField(blank=True)),
                ('spouse_name', models.CharField(blank=True, max_length=100)),
                ('contact_no', models.CharField(blank=True, max_length=50)),
                ('education_history', models.TextField(blank=True)),
                ('work_experience', models.TextField(blank=True)),
                ('language_skills', models.TextField(blank=True)),
                ('license_info', models.TextField(blank=True)),
                ('hobbies', models.TextField(blank=True)),
                ('motivation', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
