# Generated by Django 5.2.7 on 2025-10-31 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_candidate_delete_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='biodata_pdf',
            field=models.FileField(blank=True, null=True, upload_to='documents/biodata/'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='educational_doc_pdf',
            field=models.FileField(blank=True, null=True, upload_to='documents/education/'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='id_info_pdf',
            field=models.FileField(blank=True, null=True, upload_to='documents/id_info/'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='report_pdf',
            field=models.FileField(blank=True, null=True, upload_to='documents/reports/'),
        ),
    ]
