# Generated by Django 5.2.7 on 2025-10-31 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_candidate_biodata_pdf_candidate_educational_doc_pdf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_level', models.CharField(max_length=50)),
                ('school_name', models.CharField(max_length=200)),
                ('admission_year', models.IntegerField(blank=True, null=True)),
                ('admission_month', models.CharField(blank=True, max_length=20, null=True)),
                ('graduation_year', models.IntegerField(blank=True, null=True)),
                ('graduation_month', models.CharField(blank=True, max_length=20, null=True)),
                ('enrolled_years', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('full_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='student_photos/')),
                ('permanent_address', models.TextField()),
                ('present_address', models.TextField(blank=True, null=True)),
                ('age', models.IntegerField()),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=10)),
                ('passport_no', models.CharField(blank=True, max_length=20, null=True)),
                ('passport_issue_date', models.DateField(blank=True, null=True)),
                ('passport_expiry_date', models.DateField(blank=True, null=True)),
                ('height', models.CharField(blank=True, max_length=20, null=True)),
                ('weight', models.CharField(blank=True, max_length=20, null=True)),
                ('medical_report', models.TextField(blank=True, null=True)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True)),
                ('tb_status', models.CharField(blank=True, max_length=10, null=True)),
                ('visa_apply_record', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True)),
                ('visa_details', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('spouse_name', models.CharField(blank=True, max_length=100, null=True)),
                ('spouse_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('certificate_pass_year', models.CharField(blank=True, max_length=50, null=True)),
                ('certificate_name', models.CharField(blank=True, max_length=200, null=True)),
                ('language_join_year', models.CharField(blank=True, max_length=50, null=True)),
                ('organization', models.CharField(blank=True, max_length=200, null=True)),
                ('driving_license', models.CharField(blank=True, max_length=100, null=True)),
                ('license_pass_year', models.CharField(blank=True, max_length=50, null=True)),
                ('license_discretion', models.TextField(blank=True, null=True)),
                ('hobbies', models.TextField(blank=True, null=True)),
                ('motivation', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_type', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=200)),
                ('join_date', models.CharField(blank=True, max_length=50, null=True)),
                ('resign_date', models.CharField(blank=True, max_length=50, null=True)),
                ('working_years', models.IntegerField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experience', to='dashboard.student')),
            ],
        ),
        migrations.DeleteModel(
            name='Candidate',
        ),
        migrations.AddField(
            model_name='educationalhistory',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_history', to='dashboard.student'),
        ),
    ]
