# Generated by Django 5.2.7 on 2025-10-31 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_educationalhistory_student_workexperience_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('bio_data', 'Student BIO-DATA'), ('id_info', 'Student ID Information'), ('educational_doc', 'Student Educational Doc'), ('report', 'Student Report'), ('other', 'PDF')], max_length=20)),
                ('document_file', models.FileField(upload_to='student_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='dashboard.student')),
            ],
        ),
    ]
