# Generated by Django 5.2.7 on 2025-11-24 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_portal', '0001_initial'),
        ('dashboard', '0010_student_review_notes_student_reviewed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='candidate_portal.agent'),
        ),
        migrations.AddField(
            model_name='student',
            name='candidate',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student', to='candidate_portal.candidate'),
        ),
    ]
