# Generated by Django 5.2.7 on 2025-11-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_student_agent_student_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='accommodation_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='approved_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='ceo_approval_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='ceo_approval_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='expected_arrival',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='interview_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='interview_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='interview_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='interview_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='interviewer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='qualification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='stage',
            field=models.CharField(choices=[('candidate_info', 'Candidate Information'), ('select_candidate', 'Select Candidate'), ('interview_pattern', 'Interview Pattern'), ('pass_interview', 'Pass Interview'), ('ceo_approval', 'CEO Approval'), ('visa_arrival', 'Visa & Arrival'), ('completed', 'Completed')], default='candidate_info', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='visa_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
