# Generated by Django 5.2.7 on 2025-11-26 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_fix_student_stages'),
        ('dashboard', '0012_student_accommodation_status_student_approved_by_and_more'),
    ]

    operations = [
    ]
