# Generated by Django 4.2.27 on 2026-01-20 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_merge_20251126_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='passport_no',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
