# Generated by Django 4.2.27 on 2026-01-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_alter_student_passport_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='medical_report',
            field=models.FileField(blank=True, null=True, upload_to='medical_reports/'),
        ),
    ]
