# Generated by Django 4.2.27 on 2026-01-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_alter_student_medical_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='eye_lens_left',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Eye Lens - Left'),
        ),
        migrations.AddField(
            model_name='student',
            name='eye_lens_right',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Eye Lens - Right'),
        ),
    ]
