# Generated by Django 4.2.27 on 2026-01-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_student_eye_lens_left_student_eye_lens_right'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(default=18),
        ),
        migrations.AlterField(
            model_name='student',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='O+', max_length=3),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AlterField(
            model_name='student',
            name='eye_lens_left',
            field=models.CharField(default='Normal', max_length=50, verbose_name='Eye Lens - Left'),
        ),
        migrations.AlterField(
            model_name='student',
            name='eye_lens_right',
            field=models.CharField(default='Normal', max_length=50, verbose_name='Eye Lens - Right'),
        ),
        migrations.AlterField(
            model_name='student',
            name='full_name',
            field=models.CharField(default='Unknown Student', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='height',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='marital_status',
            field=models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], default='single', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='passport_expiry_date',
            field=models.DateField(default='2030-01-01'),
        ),
        migrations.AlterField(
            model_name='student',
            name='passport_issue_date',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AlterField(
            model_name='student',
            name='passport_no',
            field=models.CharField(default='UNKNOWN', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='permanent_address',
            field=models.TextField(default='Unknown'),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(default='student_photos/default.png', upload_to='student_photos/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='tb_status',
            field=models.CharField(default='negative', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='weight',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
