# Generated by Django 4.2.27 on 2026-01-29 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_alter_student_age_alter_student_blood_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='eye_lens_left',
            field=models.CharField(max_length=50, verbose_name='Eye Lens - Left'),
        ),
        migrations.AlterField(
            model_name='student',
            name='eye_lens_right',
            field=models.CharField(max_length=50, verbose_name='Eye Lens - Right'),
        ),
        migrations.AlterField(
            model_name='student',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='height',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='marital_status',
            field=models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='passport_expiry_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='passport_issue_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='passport_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='permanent_address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(upload_to='student_photos/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='tb_status',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='weight',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='document_type',
            field=models.CharField(choices=[('bio_data', 'Passport'), ('id_info', 'Citizenship/Driving'), ('educational_doc', 'Graduation/Transcript'), ('report', 'Medical Report'), ('other', 'Other PDF')], max_length=20),
        ),
    ]
