# Generated by Django 4.2.27 on 2026-01-29 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_alter_student_age_alter_student_blood_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='hobbies',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='motivation',
            field=models.TextField(null=True),
        ),
    ]
