# Generated by Django 4.2.27 on 2026-01-29 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_alter_student_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='medical_report',
        ),
    ]
