# Generated by Django 4.2.27 on 2026-01-29 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_remove_student_medical_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='family_records',
            field=models.TextField(blank=True, null=True),
        ),
    ]
