# Generated by Django 6.0.1 on 2026-01-30 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_student_family_records'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalhistory',
            name='enrolled_years',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='working_years',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
