# Generated by Django 6.0.1 on 2026-02-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_alter_educationalhistory_enrolled_years_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='passport_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='passport_issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='passport_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
