# Generated by Django 6.0.1 on 2026-02-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_alter_student_passport_expiry_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='license_discretion',
        ),
        migrations.AddField(
            model_name='student',
            name='license_pass_year_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='license_type_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
