# Generated by Django 6.0.1 on 2026-03-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_remove_student_license_discretion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='japanese_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Japanese Name (Katakana/Hiragana)'),
        ),
    ]
