# Generated by Django 4.2.27 on 2026-03-20 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0027_classroom_classstudent_attendancerecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDailyNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_date', models.DateField()),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_notes', to='dashboard.student')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='written_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-note_date', '-created_at'],
                'unique_together': {('student', 'note_date', 'teacher')},
            },
        ),
    ]
