# Generated by Django 6.0.1 on 2026-05-19 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_teacherstudentrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('material_type', models.CharField(choices=[('document', 'Document'), ('video', 'Video'), ('audio', 'Audio'), ('image', 'Image'), ('link', 'External Link'), ('other', 'Other')], default='document', max_length=20)),
                ('category', models.CharField(choices=[('lecture_notes', 'Lecture Notes'), ('homework', 'Homework'), ('study_guide', 'Study Guide'), ('assignment', 'Assignment'), ('exam_prep', 'Exam Preparation'), ('reference', 'Reference Material'), ('other', 'Other')], default='other', max_length=20)),
                ('material_file', models.FileField(blank=True, null=True, upload_to='shared_materials/')),
                ('external_link', models.URLField(blank=True, help_text='URL for external resources', null=True)),
                ('target_class', models.CharField(blank=True, help_text='Target class or group', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_materials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shared Material',
                'verbose_name_plural': 'Shared Materials',
                'ordering': ['-created_at'],
            },
        ),
    ]
