# Generated by Django 6.0.1 on 2026-09-11 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_sharedmaterial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_name', models.CharField(blank=True, max_length=200, verbose_name='Name of Certificate / Exam')),
                ('pass_year', models.CharField(blank=True, max_length=50, verbose_name='Pass Year & Month')),
                ('join_year', models.CharField(blank=True, max_length=50, verbose_name='Join Year & Month')),
                ('organization', models.CharField(blank=True, max_length=200, verbose_name='Organization / Training Center')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='dashboard.student')),
            ],
            options={
                'verbose_name': 'Student Certificate & Skill',
                'verbose_name_plural': 'Student Certificates & Skills',
                'ordering': ['-pass_year', '-created_at'],
            },
        ),
    ]
