# Generated by Django 5.2.7 on 2025-10-22 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_client',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('operation_head', 'Operation Head'), ('manager', 'Manager'), ('staff', 'Staff'), ('client', 'Recruitment Client'), ('college', 'College')], default='staff', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
    ]
