# Generated by Django 6.0.1 on 2026-03-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_is_admin_remove_user_is_client_user_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('operation_head', 'Operation Head'), ('manager', 'Manager'), ('staff', 'Staff'), ('client', 'Recruitment Client'), ('college', 'College'), ('teacher', 'Teacher')], default='staff', max_length=20),
        ),
    ]
