# Generated by Django 4.2.27 on 2025-12-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sswadmission', '0002_alter_feeinstallment_options_feeinstallment_late_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='batch',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
