# Generated by Django 4.2.27 on 2025-12-31 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sswadmission', '0003_alter_student_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feepayment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('online_payment', 'Online Payment'), ('cheque', 'Cheque'), ('card', 'Credit/Debit Card'), ('upi', 'Wallet')], default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='country',
            field=models.CharField(default='Nepal', max_length=100),
        ),
    ]
