# Generated by Django 5.2.7 on 2025-11-21 08:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('agent_code', models.CharField(editable=False, max_length=20, unique=True)),
                ('pin_code', models.CharField(editable=False, max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('max_candidates', models.PositiveIntegerField(default=100, help_text='Maximum candidates allowed for this agent')),
                ('current_candidate_count', models.PositiveIntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'agents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('student_id', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_access', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='candidate_portal.agent')),
            ],
            options={
                'db_table': 'candidates',
                'ordering': ['-created_at'],
                'unique_together': {('agent', 'email')},
            },
        ),
    ]
