# Generated by Django 5.2.7 on 2025-11-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='agent_code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='pin_code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
