# Generated by Django 5.2.7 on 2025-11-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_portal', '0002_alter_agent_agent_code_alter_agent_pin_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='agent_code',
            field=models.CharField(blank=True, help_text='Leave blank to auto-generate', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='pin_code',
            field=models.CharField(blank=True, help_text='Leave blank to auto-generate', max_length=10, unique=True),
        ),
    ]
