# Generated by Django 5.2.7 on 2025-12-04 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_portal', '0003_alter_agent_agent_code_alter_agent_pin_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='agent_code',
            field=models.CharField(blank=True, help_text='Leave blank to auto-generate', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='max_candidates',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='agent',
            name='pin_code',
            field=models.CharField(blank=True, help_text='Leave blank to auto-generate', max_length=10, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='candidate_portal.agent')),
            ],
            options={
                'db_table': 'contracts',
                'ordering': ['-start_date'],
            },
        ),
    ]
