# Generated by Django 5.2.7 on 2025-12-04 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_portal', '0004_alter_agent_agent_code_alter_agent_max_candidates_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='candidate',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='agent',
            name='agent_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='current_candidate_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='agent',
            name='pin_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='last_access',
        ),
    ]
