# Generated by Django 5.2.7 on 2025-11-15 06:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_id', models.CharField(max_length=50, unique=True, verbose_name='College ID')),
                ('college_name_english', models.CharField(max_length=255, verbose_name='College Name (English)')),
                ('college_name_japanese', models.CharField(blank=True, max_length=255, verbose_name='College Name (Japanese)')),
                ('phone_no', models.CharField(blank=True, max_length=20, verbose_name='Phone No.')),
                ('fax_no', models.CharField(blank=True, max_length=20, verbose_name='Fax No.')),
                ('email', models.EmailField(max_length=254, verbose_name='College Email ID')),
                ('website', models.URLField(blank=True, verbose_name='Home Page')),
                ('head_office_address', models.TextField(verbose_name='Head Office Address')),
                ('corporate_office_address', models.TextField(blank=True, verbose_name='Corporate Office Address')),
                ('representative_name', models.CharField(max_length=255, verbose_name='Representative Name')),
                ('representative_mobile', models.CharField(max_length=20, verbose_name='Representative Mobile')),
                ('college_type', models.CharField(max_length=255, verbose_name='Type of College')),
                ('agreement_date', models.DateField(verbose_name='Agreement Date')),
                ('expire_date', models.DateField(verbose_name='Expire Date')),
                ('agreement_type', models.CharField(choices=[('student', 'Student'), ('other', 'Other')], max_length=10, verbose_name='Agreement Type')),
                ('agreement_doc', models.FileField(blank=True, null=True, upload_to='college_docs/agreements/', verbose_name='Agreement Document')),
                ('interview_pass_doc', models.FileField(blank=True, null=True, upload_to='college_docs/interview_pass/', verbose_name='Interview Pass Document')),
                ('visa_apply_doc', models.FileField(blank=True, null=True, upload_to='college_docs/visa_apply/', verbose_name='Visa Apply Document')),
                ('ceo_visa_doc', models.FileField(blank=True, null=True, upload_to='college_docs/ceo_visa/', verbose_name='CEO Visa Document')),
                ('other_doc', models.FileField(blank=True, null=True, upload_to='college_docs/other/', verbose_name='Other Document')),
                ('pdf_doc_1', models.FileField(blank=True, null=True, upload_to='college_docs/pdf/', verbose_name='PDF Document 1')),
                ('pdf_doc_2', models.FileField(blank=True, null=True, upload_to='college_docs/pdf/', verbose_name='PDF Document 2')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'College',
                'verbose_name_plural': 'Colleges',
            },
        ),
        migrations.CreateModel(
            name='CollegeYearlyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2024)], verbose_name='Year')),
                ('yearly_student_no', models.PositiveIntegerField(default=0, verbose_name='Yearly Student No.')),
                ('interview_attend_no', models.PositiveIntegerField(default=0, verbose_name='Interview Attend No.')),
                ('interview_pass_no', models.PositiveIntegerField(default=0, verbose_name='Interview Pass No.')),
                ('visa_application_no', models.PositiveIntegerField(default=0, verbose_name='Visa Application No.')),
                ('ceo_success_no', models.PositiveIntegerField(default=0, verbose_name='CEO Success No.')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearly_data', to='company.college')),
            ],
            options={
                'verbose_name': 'College Yearly Data',
                'verbose_name_plural': 'College Yearly Data',
                'unique_together': {('college', 'year')},
            },
        ),
    ]
