# Generated by Django 4.2.27 on 2026-01-20 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import other_documents.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('document_type', models.CharField(choices=[('audit', 'Audit Report'), ('tax', 'Tax Filing'), ('financial', 'Financial Statement'), ('contract', 'Contract/Agreement'), ('invoice', 'Invoice/Receipt'), ('compliance', 'Compliance Document'), ('miscellaneous', 'Miscellaneous')], max_length=50)),
                ('file', models.FileField(upload_to=other_documents.models.get_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='pending', max_length=20)),
                ('fiscal_year', models.IntegerField(default=2026)),
                ('is_confidential', models.BooleanField(default=False)),
                ('client_name', models.CharField(blank=True, max_length=200)),
                ('project_code', models.CharField(blank=True, max_length=50)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('file_size', models.BigIntegerField(default=0)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Financial Document',
                'verbose_name_plural': 'Financial Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='other_documents.financialdocument')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
