# Generated by Django 6.0.1 on 2026-06-24 08:52

import django.db.models.deletion
import translation.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('keywords', models.TextField(help_text="Comma-separated keywords for auto-detection (e.g. 'transcript,grade sheet,marks')")),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Document Type',
                'verbose_name_plural': 'Document Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('original_file', models.FileField(upload_to=translation.models.document_upload_path)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('image', 'Image (JPG/PNG)'), ('scanned_pdf', 'Scanned PDF')], max_length=20)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('extracting', 'Extracting Text'), ('extracted', 'Text Extracted'), ('translating', 'Translating'), ('translated', 'Translated'), ('reviewing', 'Under Review'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('extracted_text', models.TextField(blank=True, help_text='Extracted English text')),
                ('translated_text', models.TextField(blank=True, help_text='Translated Japanese text')),
                ('translated_file', models.FileField(blank=True, null=True, upload_to=translation.models.translated_upload_path)),
                ('notes', models.TextField(blank=True, help_text='Staff notes about this document')),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_translations', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_translations', to=settings.AUTH_USER_MODEL)),
                ('auto_detected_type', models.ForeignKey(blank=True, help_text='Auto-detected document type (may differ from manual override)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_detected_documents', to='translation.documenttype')),
                ('document_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='translation.documenttype')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TranslationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('upload', 'Document Uploaded'), ('extract', 'Text Extracted'), ('translate', 'Translation Completed'), ('review', 'Review Completed'), ('edit', 'Translation Edited'), ('download', 'DOCX Downloaded'), ('tm_hit', 'Translation Memory Hit'), ('tm_miss', 'Translation Memory Miss'), ('error', 'Error Occurred')], max_length=20)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='translation.document')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Translation History',
                'verbose_name_plural': 'Translation Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TranslationMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_text', models.TextField(db_index=True)),
                ('japanese_text', models.TextField()),
                ('source', models.CharField(choices=[('google', 'Google Translate'), ('manual', 'Manual Entry'), ('review', 'Staff Review'), ('import', 'Imported')], default='google', max_length=50)),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Number of times this translation was reused')),
                ('is_verified', models.BooleanField(default=False, help_text='Has been verified by staff')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translation_memories', to='translation.documenttype')),
            ],
            options={
                'verbose_name': 'Translation Memory',
                'verbose_name_plural': 'Translation Memories',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['-created_at'], name='translation_created_c4396f_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status'], name='translation_status_c9a01e_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['document_type'], name='translation_documen_d7b6fa_idx'),
        ),
        migrations.AddIndex(
            model_name='translationhistory',
            index=models.Index(fields=['-created_at'], name='translation_created_913d67_idx'),
        ),
        migrations.AddIndex(
            model_name='translationhistory',
            index=models.Index(fields=['action'], name='translation_action_7ee1b6_idx'),
        ),
        migrations.AddIndex(
            model_name='translationmemory',
            index=models.Index(fields=['english_text'], name='translation_english_4a393a_idx'),
        ),
        migrations.AddIndex(
            model_name='translationmemory',
            index=models.Index(fields=['document_type'], name='translation_documen_539b54_idx'),
        ),
        migrations.AddIndex(
            model_name='translationmemory',
            index=models.Index(fields=['-usage_count'], name='translation_usage_c_1ae770_idx'),
        ),
        migrations.AddIndex(
            model_name='translationmemory',
            index=models.Index(fields=['-updated_at'], name='translation_updated_d83961_idx'),
        ),
    ]
