# Generated by Django 6.0.1 on 2026-06-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='layout_data',
            field=models.JSONField(blank=True, help_text='Layout info: text blocks with positions, image positions per page', null=True),
        ),
    ]
