# Generated by Django 6.0.1 on 2026-06-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0002_add_layout_data_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='layout_data',
            field=models.TextField(blank=True, default='', help_text='JSON: text block positions, image positions per page'),
        ),
    ]
