# Generated by Django 4.2.27 on 2026-01-20 12:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import guarantee_letter.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('passport_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JobGuaranteeLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('source', models.CharField(choices=[('uploaded', 'Uploaded PDF'), ('created', 'Created from Template')], default='created', max_length=20)),
                ('candidate_name', models.CharField(max_length=200)),
                ('candidate_email', models.EmailField(max_length=254)),
                ('candidate_phone', models.CharField(blank=True, max_length=20)),
                ('passport_number', models.CharField(blank=True, max_length=50, null=True)),
                ('job_title', models.CharField(max_length=200)),
                ('company_name', models.CharField(blank=True, max_length=150)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('letter_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('internship', 'Internship'), ('temporary', 'Temporary')], default='full_time', max_length=20)),
                ('issue_date', models.DateField(default=datetime.date.today)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('salary_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_currency', models.CharField(blank=True, default='USD', max_length=10)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=guarantee_letter.models.upload_to)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('generated_content', models.TextField(blank=True)),
                ('generated_pdf', models.FileField(blank=True, null=True, upload_to='generated_letters/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('pending', 'Pending'), ('verified', 'Verified'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('confirmation_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letters', to='guarantee_letter.client')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_guarantee_letters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='LetterLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('upload', 'Uploaded'), ('create', 'Created'), ('verify', 'Verified'), ('reject', 'Rejected'), ('update', 'Updated'), ('download', 'Downloaded'), ('delete', 'Deleted')], max_length=20)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='guarantee_letter.jobguaranteeletter')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobGuaranteeLetterTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='jobguaranteeletter',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='guarantee_letter.jobguaranteelettertemplate'),
        ),
        migrations.AddField(
            model_name='jobguaranteeletter',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_guarantee_letters', to=settings.AUTH_USER_MODEL),
        ),
    ]
