# Generated by Django 5.2.7 on 2025-11-13 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('full_name', models.CharField(max_length=100)),
                ('marital_status', models.CharField(max_length=20)),
                ('permanent_address', models.TextField()),
                ('present_address', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff_photos/')),
                ('passport_no', models.CharField(blank=True, max_length=50)),
                ('date_of_issue', models.DateField(blank=True, null=True)),
                ('issue_from', models.CharField(blank=True, max_length=50)),
                ('date_of_birth', models.DateField()),
                ('eye_lense_right', models.CharField(blank=True, max_length=20)),
                ('eye_lense_left', models.CharField(blank=True, max_length=20)),
                ('blood_group', models.CharField(blank=True, max_length=10)),
                ('phone_no', models.CharField(max_length=20)),
                ('email_id', models.EmailField(max_length=254)),
                ('spouse_name', models.CharField(blank=True, max_length=100)),
                ('family_records', models.TextField(blank=True)),
                ('contact_no', models.CharField(blank=True, max_length=20)),
                ('hobbies', models.TextField(blank=True)),
                ('motivation', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='EducationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_level', models.CharField(max_length=50)),
                ('school_name', models.CharField(max_length=100)),
                ('admission_year', models.IntegerField(blank=True, null=True)),
                ('admission_month', models.IntegerField(blank=True, null=True)),
                ('graduation_year', models.IntegerField(blank=True, null=True)),
                ('graduation_month', models.IntegerField(blank=True, null=True)),
                ('enrolled_years', models.IntegerField(blank=True, null=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.staff')),
            ],
        ),
        migrations.CreateModel(
            name='DrivingLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_year_month', models.CharField(max_length=20)),
                ('license_discretion', models.CharField(max_length=100)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.staff')),
            ],
        ),
        migrations.CreateModel(
            name='CertificateOfSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_year_month', models.CharField(max_length=20)),
                ('certificate_name', models.CharField(max_length=100)),
                ('join_year_month', models.CharField(max_length=20)),
                ('organization', models.CharField(max_length=100)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.staff')),
            ],
        ),
        migrations.CreateModel(
            name='WorkingExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_work', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('date_join', models.DateField()),
                ('date_resign', models.DateField(blank=True, null=True)),
                ('years_worked', models.FloatField(blank=True, null=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.staff')),
            ],
        ),
    ]
