# Generated by Django 5.2.7 on 2025-11-13 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=50, unique=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('full_name', models.CharField(max_length=200)),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], max_length=20)),
                ('permanent_address', models.TextField()),
                ('present_address', models.TextField()),
                ('candidate_photo', models.ImageField(blank=True, null=True, upload_to='staff_photos/')),
                ('id_passport_no', models.CharField(max_length=50)),
                ('date_of_issue', models.DateField(blank=True, null=True)),
                ('issue_from', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('eye_lense_right', models.CharField(blank=True, max_length=20)),
                ('eye_lense_left', models.CharField(blank=True, max_length=20)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('phone_no', models.CharField(max_length=20)),
                ('email_id', models.EmailField(max_length=254)),
                ('spouse_name', models.CharField(blank=True, max_length=200)),
                ('contact_no', models.CharField(blank=True, max_length=20)),
                ('hobbies', models.TextField(blank=True)),
                ('motivation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Staff Registration',
                'verbose_name_plural': 'Staff Registrations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='educationhistory',
            name='staff',
        ),
        migrations.AlterModelOptions(
            name='drivinglicense',
            options={'verbose_name': 'Driving License', 'verbose_name_plural': 'Driving Licenses'},
        ),
        migrations.AlterModelOptions(
            name='workingexperience',
            options={'ordering': ['-join_year'], 'verbose_name': 'Working Experience', 'verbose_name_plural': 'Working Experiences'},
        ),
        migrations.RemoveField(
            model_name='drivinglicense',
            name='license_discretion',
        ),
        migrations.RemoveField(
            model_name='drivinglicense',
            name='pass_year_month',
        ),
        migrations.RemoveField(
            model_name='workingexperience',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='workingexperience',
            name='date_join',
        ),
        migrations.RemoveField(
            model_name='workingexperience',
            name='date_resign',
        ),
        migrations.RemoveField(
            model_name='workingexperience',
            name='years_worked',
        ),
        migrations.AddField(
            model_name='drivinglicense',
            name='discretion_of_license',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='drivinglicense',
            name='pass_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drivinglicense',
            name='pass_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workingexperience',
            name='join_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workingexperience',
            name='join_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workingexperience',
            name='name_of_company',
            field=models.CharField(default=10, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workingexperience',
            name='resign_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workingexperience',
            name='resign_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workingexperience',
            name='working_years',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='workingexperience',
            name='type_of_work',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='SkillsTrainingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_year', models.IntegerField(blank=True, null=True)),
                ('pass_month', models.IntegerField(blank=True, null=True)),
                ('name_of_training', models.CharField(max_length=300)),
                ('join_year', models.IntegerField(blank=True, null=True)),
                ('join_month', models.IntegerField(blank=True, null=True)),
                ('organization', models.CharField(max_length=300)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_status', to='manager.staffregistration')),
            ],
            options={
                'verbose_name': 'Skills Training Status',
                'verbose_name_plural': 'Skills Training Statuses',
                'ordering': ['-pass_year'],
            },
        ),
        migrations.CreateModel(
            name='EducationalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_level', models.CharField(choices=[('Primary', 'Primary School'), ('Junior', 'Junior H School'), ('Higher', 'Higher S School'), ('College', 'College / University'), ('Graduate', 'Graduate University'), ('PostGraduate', 'Post Graduate University'), ('Other', 'Other School')], max_length=20)),
                ('name_of_school', models.CharField(max_length=300)),
                ('admission_year', models.IntegerField(blank=True, null=True)),
                ('admission_month', models.IntegerField(blank=True, null=True)),
                ('graduation_year', models.IntegerField(blank=True, null=True)),
                ('graduation_month', models.IntegerField(blank=True, null=True)),
                ('enrolled_years', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_history', to='manager.staffregistration')),
            ],
            options={
                'verbose_name': 'Educational History',
                'verbose_name_plural': 'Educational Histories',
                'ordering': ['pass_level'],
            },
        ),
        migrations.CreateModel(
            name='CertificateOfSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_year', models.IntegerField(blank=True, null=True)),
                ('pass_month', models.IntegerField(blank=True, null=True)),
                ('name_of_certificate', models.CharField(max_length=300)),
                ('join_year', models.IntegerField(blank=True, null=True)),
                ('join_month', models.IntegerField(blank=True, null=True)),
                ('organization', models.CharField(max_length=300)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='manager.staffregistration')),
            ],
            options={
                'verbose_name': 'Certificate of Skills',
                'verbose_name_plural': 'Certificates of Skills',
                'ordering': ['-pass_year'],
            },
        ),
        migrations.AlterField(
            model_name='drivinglicense',
            name='staff',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driving_license', to='manager.staffregistration'),
        ),
        migrations.AlterField(
            model_name='workingexperience',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experience', to='manager.staffregistration'),
        ),
        migrations.DeleteModel(
            name='CertificateOfSkill',
        ),
        migrations.DeleteModel(
            name='EducationHistory',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
