# Generated by Django 5.2.7 on 2025-11-15 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_staffregistration_remove_educationhistory_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffregistration',
            name='staff_bio_data_pdf',
            field=models.FileField(blank=True, help_text='Upload Staff Bio Data PDF', null=True, upload_to='staff_documents/bio_data/'),
        ),
        migrations.AddField(
            model_name='staffregistration',
            name='staff_id_doc_pdf',
            field=models.FileField(blank=True, help_text='Upload Staff ID Document PDF', null=True, upload_to='staff_documents/id_docs/'),
        ),
        migrations.AddField(
            model_name='staffregistration',
            name='staff_login_id_pdf',
            field=models.FileField(blank=True, help_text='Upload Staff Login ID PDF', null=True, upload_to='staff_documents/login_ids/'),
        ),
        migrations.AddField(
            model_name='staffregistration',
            name='staff_login_report_pdf',
            field=models.FileField(blank=True, help_text='Upload Staff Login Report PDF', null=True, upload_to='staff_documents/login_reports/'),
        ),
    ]
