# Generated by Django 4.2.27 on 2025-12-11 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_staffregistration_staff_bio_data_pdf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=150)),
                ('branch_name', models.CharField(max_length=150)),
                ('account_no', models.CharField(max_length=50)),
                ('account_holder_name', models.CharField(max_length=150)),
            ],
        ),
    ]
