# Generated by Django 4.2.27 on 2025-12-11 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_bankinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankinformation',
            name='staff',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bank_info', to='manager.staffregistration'),
            preserve_default=False,
        ),
    ]
