# Generated by Django 4.2.27 on 2026-03-26 17:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_bankinformation_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffregistration',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3),
        ),
        migrations.AlterField(
            model_name='staffregistration',
            name='eye_lense_left',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='staffregistration',
            name='eye_lense_right',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='staffregistration',
            name='hobbies',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='staffregistration',
            name='issue_from',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='staffregistration',
            name='motivation',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='staffregistration',
            name='phone_no',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Phone number must be exactly 10 digits.')]),
        ),
        migrations.AlterField(
            model_name='staffregistration',
            name='staff_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
