# Generated by Django 6.0.1 on 2026-04-08 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_alter_staffregistration_blood_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffregistration',
            name='staff_bio_data_pdf',
            field=models.FileField(default='', help_text='Upload Staff Bio Data PDF', upload_to='staff_documents/bio_data/'),
        ),
    ]
