# Generated by Django 6.0.1 on 2026-05-18 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_alter_staffregistration_staff_bio_data_pdf'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScannedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=200)),
                ('document_type', models.CharField(choices=[('passport', 'Passport'), ('citizenship', 'Citizenship'), ('medical', 'Medical Report'), ('education', 'Education Certificate'), ('photo', 'Photo'), ('visa', 'Visa Document'), ('other', 'Other')], default='other', max_length=20)),
                ('candidate_name', models.CharField(blank=True, help_text='Associated candidate name', max_length=200)),
                ('candidate_id', models.CharField(blank=True, help_text='Associated candidate ID', max_length=50)),
                ('document_file', models.FileField(upload_to='scanned_documents/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scanned Document',
                'verbose_name_plural': 'Scanned Documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
