# Generated by Django 4.2.27 on 2026-05-24 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_scanneddocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanneddocument',
            name='file_size',
            field=models.PositiveIntegerField(default=0, help_text='File size in bytes'),
        ),
        migrations.AddField(
            model_name='scanneddocument',
            name='page_count',
            field=models.PositiveIntegerField(default=1, help_text='Number of pages (for PDFs)'),
        ),
    ]
