# Generated by Django 6.0.1 on 2026-09-03 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_scanneddocument_file_size_scanneddocument_page_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_snapshot', models.CharField(blank=True, help_text='Username at time of activity', max_length=150)),
                ('role_snapshot', models.CharField(blank=True, help_text='Role at time of activity', max_length=20)),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('task_assigned', 'Task Assigned'), ('task_status_update', 'Task Status Update'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('view', 'View'), ('export', 'Export'), ('scan', 'Scan / Upload'), ('other', 'Other')], default='other', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('path', models.CharField(blank=True, max_length=500)),
                ('method', models.CharField(blank=True, max_length=10)),
                ('extra_data', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Activity Log',
                'verbose_name_plural': 'Staff Activity Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='manager_sta_user_id_f81230_idx'), models.Index(fields=['action'], name='manager_sta_action_f276f9_idx'), models.Index(fields=['-timestamp'], name='manager_sta_timesta_aa7cd6_idx')],
            },
        ),
    ]
